In [3]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [7]:
# This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray
df= load_iris()
dir(df)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [45]:
df.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [54]:
# df.target contains the numeric labels (also called class indices) for each flower sample in the Iris dataset.
# Each sample (row in df.data) belongs to one of three species of Iris flowers:
# 0 → Iris-setosa
# 1 → Iris-versicolor
# 2 → Iris-virginica
df.target[0:150]
# first 50 0s are of Iris-setosa
# second 50 1s are of Iris-versicolor
# third 50 2s are of Iris-virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
df.target_names[0:5]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [47]:
df.feature_names[0:5]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [25]:
df.data_module[0:12]

'sklearn.data'

In [29]:
df.filename[0:5]

'iris.'

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.data, df.target, test_size=0.2)

In [58]:
model= LogisticRegression()
model.fit(X_train, Y_train)

c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [60]:
model.predict(X_train)

array([0, 2, 2, 2, 2, 1, 0, 2, 1, 2, 2, 0, 0, 2, 1, 2, 2, 0, 0, 0, 0, 0,
       1, 2, 0, 1, 2, 2, 2, 2, 1, 0, 0, 1, 0, 2, 2, 2, 2, 1, 1, 2, 0, 2,
       2, 1, 1, 1, 2, 0, 1, 0, 2, 1, 1, 1, 2, 2, 0, 2, 2, 0, 2, 1, 1, 0,
       2, 0, 0, 2, 0, 0, 1, 2, 0, 1, 1, 2, 0, 1, 1, 0, 0, 1, 1, 2, 0, 1,
       0, 2, 2, 1, 0, 2, 1, 1, 2, 1, 1, 1, 0, 2, 1, 1, 2, 0, 0, 2, 0, 2,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 2])

In [61]:
model.score(X_test, Y_test)

1.0

In [65]:
model.predict(df.data[[67]])
# The response is array([1]) that means its Iris-versicolor

array([1])